/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jscarabeo;

import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author lazzarin_andrea
 */
public class Tabellone extends javax.swing.JFrame {

    /**
     * Creates new form Tabellone
     */
    DatiCondivisi d;
    GestoreGioco gg;
    MyButtons temp1 = null;

    public Tabellone(DatiCondivisi d) throws IOException, InterruptedException {
        initComponents();

        this.d = d;
        d.setTabellone(this);

        nick1.setText(d.getMyNickname());

        gg = new GestoreGioco(d);
        gg.start();

        generaBottoni();
    }

    public void setMano(int i, Lettera lettera) {

//        switch (i) {
//            case 0 -> {
//                this.btn0.setIcon(lettera.getImg());
//                this.btn0.setName(generaNome(lettera, "btn0$"));
//            }
//            case 1 -> {
//                this.btn1.setIcon(lettera.getImg());
//                this.btn1.setName(generaNome(lettera, "btn1$"));
//            }
//            case 2 -> {
//                this.btn2.setIcon(lettera.getImg());
//                this.btn2.setName(generaNome(lettera, "btn2$"));
//            }
//            case 3 -> {
//                this.btn3.setIcon(lettera.getImg());
//                this.btn3.setName(generaNome(lettera, "btn3$"));
//            }
//            case 4 -> {
//                this.btn4.setIcon(lettera.getImg());
//                this.btn4.setName(generaNome(lettera, "btn4$"));
//            }
//            case 5 -> {
//                this.btn5.setIcon(lettera.getImg());
//                this.btn5.setName(generaNome(lettera, "btn5$"));
//            }
//            case 6 -> {
//                this.btn6.setIcon(lettera.getImg());
//                this.btn6.setName(generaNome(lettera, "btn6$"));
//            }
//            case 7 -> {
//                this.btn7.setIcon(lettera.getImg());
//                this.btn7.setName(generaNome(lettera, "btn7$"));
//            }
//        }
    }

    private String generaNome(Lettera l, String NomeAttuale) {
        String nome = NomeAttuale.substring(0, NomeAttuale.indexOf("$"));
        nome += Character.toString(l.getLettera());
        return nome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nick1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nick2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInvia = new javax.swing.JButton();
        jButton307 = new javax.swing.JButton();
        jButton308 = new javax.swing.JButton();
        jButton309 = new javax.swing.JButton();
        jButton310 = new javax.swing.JButton();
        jButton311 = new javax.swing.JButton();
        jButton313 = new javax.swing.JButton();
        jButton314 = new javax.swing.JButton();
        btn99$ = new javax.swing.JButton();
        btnRipesca = new javax.swing.JButton();
        btnResa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1070, 900));
        setSize(new java.awt.Dimension(1070, 900));

        jLabel1.setText("Player: ");

        nick1.setText("...");

        jLabel2.setText("Player: ");

        nick2.setText("...");

        jLabel3.setText("Score:");

        score1.setText("0");

        score2.setText("0");

        jLabel4.setText("Score:");

        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel5.setText("SCARABEO");

        btnInvia.setText("INVIA");
        btnInvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInviaActionPerformed(evt);
            }
        });

        jButton307.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jscarabeo/images/tassello.png"))); // NOI18N
        jButton307.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton307.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton307.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton308.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jscarabeo/images/tassello.png"))); // NOI18N
        jButton308.setToolTipText("");
        jButton308.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton308.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton308.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton309.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jscarabeo/images/tassello.png"))); // NOI18N
        jButton309.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton309.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton309.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton310.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jscarabeo/images/tassello.png"))); // NOI18N
        jButton310.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton310.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton310.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton311.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jscarabeo/images/tassello.png"))); // NOI18N
        jButton311.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton311.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton311.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton313.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jscarabeo/images/tassello.png"))); // NOI18N
        jButton313.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton313.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton313.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton314.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jscarabeo/images/tassello.png"))); // NOI18N
        jButton314.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton314.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton314.setPreferredSize(new java.awt.Dimension(40, 40));

        btn99$.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jscarabeo/images/tassello.png"))); // NOI18N
        btn99$.setMaximumSize(new java.awt.Dimension(40, 40));
        btn99$.setMinimumSize(new java.awt.Dimension(40, 40));
        btn99$.setPreferredSize(new java.awt.Dimension(40, 40));

        btnRipesca.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnRipesca.setText("RIPESCA");
        btnRipesca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRipescaActionPerformed(evt);
            }
        });

        btnResa.setText("RESA");
        btnResa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nick1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(score1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(329, 329, 329)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nick2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(score2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnResa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInvia)
                            .addComponent(btnRipesca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton311, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))
                                .addComponent(jButton308, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton313, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton314, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton307, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton310, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn99$, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn99$, jButton307, jButton308, jButton309, jButton310, jButton311, jButton313, jButton314});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nick1)
                            .addComponent(jLabel2)
                            .addComponent(nick2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(score1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(score2))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(jButton308, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton311, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn99$, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton313, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton314, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton307, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton310, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRipesca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(btnResa)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn99$, jButton307, jButton308, jButton309, jButton310, jButton311, jButton313, jButton314});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInviaActionPerformed
        //parola da inviare
        //sequenza di messaggi aggiunti alla listPacchettiDaInviare
        gg.setConfermato(true);
    }//GEN-LAST:event_btnInviaActionPerformed

    private void btnRipescaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRipescaActionPerformed
        gg.ManoDaRifare();
    }//GEN-LAST:event_btnRipescaActionPerformed

    private void btnResaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "TI SEI RITIRATO!");
        gg.resa();
    }//GEN-LAST:event_btnResaActionPerformed

    private void metodoGeneraleButtons(ActionEvent evt) {
        MyButtons b = (MyButtons) evt.getSource();
        //salvo in un buffer immagine e nome

        //entro se: 1- buffer vuoto e button premuto con lettera    2- buffer pieno e button premuto vuoto
        if (temp1 == null && b.getIcon() != null) {
            temp1 = b;
        } else if (temp1 != null && b.getIcon() == null) {

            //sposto
            b.setLettera(temp1.getLettera());
            b.setIcon(temp1.getIcon());

            gg.ComponiParola(b.getLettera().getLettera(), b.getX(), b.getY(), b.getBonus());

            //svuoto buffer
            temp1 = null;
        }
    }

    private void generaBottoni() {
        int width = 50;
        int x = 95;
        int y = 65;
        MyButtons btn;

        for (int i = 0; i < 17; i++) {
            for (int j = 0; j < 17; j++) {
                btn = new MyButtons(j, i);
                btn.setBounds(x, y, width, width);
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        metodoGeneraleButtons(e);
                    }
                });
                this.add(btn);
                x += 45;
            }
            y += 45;
            x = 95;
        }

        x = 6;
        y = 157;

        for (int z = 0; z < 8; z++) {
            btn = new MyButtons(-1, -1);
            btn.setBounds(6, y, width, width);
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    metodoGeneraleButtons(e);
                }
            });

            this.add(btn);
            y += 45;
        }

    }

    public void setOpponentNickname() {
        nick2.setText(d.getOpponentNickname());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Tabellone(new DatiCondivisi()).setVisible(true);
            } catch (UnknownHostException | SocketException ex) {
                Logger.getLogger(Login.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Tabellone.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        });

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn99$;
    private javax.swing.JButton btnInvia;
    private javax.swing.JButton btnResa;
    private javax.swing.JButton btnRipesca;
    private javax.swing.JButton jButton307;
    private javax.swing.JButton jButton308;
    private javax.swing.JButton jButton309;
    private javax.swing.JButton jButton310;
    private javax.swing.JButton jButton311;
    private javax.swing.JButton jButton313;
    private javax.swing.JButton jButton314;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nick1;
    private javax.swing.JLabel nick2;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    // End of variables declaration//GEN-END:variables

}
